-- seven_day_moving_average_prcp.sql

SELECT
  DATE,
  PRCP,
  (
    COALESCE(CAST(LAG(PRCP, 3) OVER (ORDER BY DATE) AS DOUBLE), 0) +
    COALESCE(CAST(LAG(PRCP, 2) OVER (ORDER BY DATE) AS DOUBLE), 0) +
    COALESCE(CAST(LAG(PRCP, 1) OVER (ORDER BY DATE) AS DOUBLE), 0) +
    COALESCE(CAST(PRCP AS DOUBLE), 0) +
    COALESCE(CAST(LEAD(PRCP, 1) OVER (ORDER BY DATE) AS DOUBLE), 0) +
    COALESCE(CAST(LEAD(PRCP, 2) OVER (ORDER BY DATE) AS DOUBLE), 0) +
    COALESCE(CAST(LEAD(PRCP, 3) OVER (ORDER BY DATE) AS DOUBLE), 0)
  ) / 7 AS seven_day_moving_avg_prcp
FROM central_park_weather
ORDER BY DATE;
